// This file was auto-generated by ML.NET Model Builder. 

using System;
using ImageRecognition1ML.Model;

namespace ImageRecognition1
{
    class Program
    {
        static void Main(string[] args)
        {
            Debug.WriteLine("Object is not valid for this category");

            // Add input data
            var input = new ModelInput();

            input.ImageSource = @"C:\Users\Eran Heymann\Desktop\Eran Sint-Maartenscollege\6v\Car models for inf2 project\car 91.png";

            // Load model and predict output of sample data
            ModelOutput result = ConsumeModel.Predict(input);

            Debug.WriteLine(result.Prediction);
            Console.WriteLine(result.Prediction)

            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                ImageSource = @"C:\Users\Eran Heymann\Desktop\Eran Sint-Maartenscollege\6v\Car models for inf2 project\car 91.png",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Label with predicted Label from sample data...\n\n");
            Console.WriteLine($"ImageSource: {sampleData.ImageSource}");
            Console.WriteLine($"\n\nPredicted Label value {predictionResult.Prediction} \nPredicted Label scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
